name: Deploy feature to ftp

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Tag to deploy"
        required: true
        type: string

jobs:
  deploy-feature:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.tags }}
      url: https://github.com

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: "setup-envs"
        name: Setup envs
        run: |
          echo "secre=${{ secrets.JJ }}"
          echo "env=${{ vars.HAHA }}"
